### ISSUE TITLE
pandas_profiling .exe error

### ISSUE THREAD

**Issue by Bilgehanaygn** [ydataai/pandas-profiling#942]
I have a small application which imports pandas_profiling and runs fine when I run the code in editor. The problem is when I convert applicaiton into .exe, I got an error which says: "ValueError: The 'pandas_profiling' package was not installed in a way that PackageLoader understands.". 

I have tried many ways to resolve the problem, tried different versions, fetch package to local etc. still the same error...

Is the package appropriate to use with .exe

Full version of error: (data_profiling.py is my small class which imports pandas_profiling)
Traceback (most recent call last):
  File "main.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "data_profiling.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pandas_profiling\__init__.py", line 6, in <module>
    from pandas_profiling.controller import pandas_decorator
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pandas_profiling\controller\pandas_decorator.py", line 4, in <module>
    from pandas_profiling.profile_report import ProfileReport
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pandas_profiling\profile_report.py", line 27, in <module>
    from pandas_profiling.report.presentation.flavours.html.templates import (
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pandas_profiling\report\presentation\flavours\html\__init__.py", line 1, in <module>
    from pandas_profiling.report.presentation.flavours.html.alerts import HTMLAlerts
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pandas_profiling\report\presentation\flavours\html\collapse.py", line 2, in <module>
    from pandas_profiling.report.presentation.flavours.html import templates
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pandas_profiling\report\presentation\flavours\html\templates.py", line 11, in <module>
    package_loader = jinja2.PackageLoader(
  File "jinja2\loaders.py", line 319, in __init__
ValueError: The 'pandas_profiling' package was not installed in a way that PackageLoader understands.

**Comment by sbrugman** [comment]
The package is not optimized to be embedded, but considering the interest we can treat this as a feature request, and welcome the community to contribute.

Specifically, `pandas-profiling` should work as expected when embedded with PyInstaller or similar. 
The first issue that needs to be tackled is that the [jinja2 `PackageLoader`](https://github.com/ydataai/pandas-profiling/blob/develop/src/pandas_profiling/report/presentation/flavours/html/templates.py) needs to be made compatible with this approach (in order to be able to find the path to the templates).

@Bilgehanaygn would you be interested to resolving this issue and contributing a pull request?

**Comment by sbrugman** [comment]
The first step to embedding in PyInstaller is to ensure the are resolved correctly after installation. A fix for the template could be:
```python
# Initializing Jinja
if getattr(sys, 'frozen', False):
    # Support for PyInstaller
    bundle_dir = sys._MEIPASS
    package_loader = jinja2.FileSystemLoader(bundle_dir)
else:
    package_loader = jinja2.PackageLoader(
        "pandas_profiling", "report/presentation/flavours/html/templates"
    )
```

Then, by including the templates and ensuring the configuration files are present at the right location, one is much closer towards being able to creating a functioning executable. 

Leaving this here as a starting point for anyone particularly interested in the feature. Feel free to reach out here or on Slack if you're interested in contributing this feature.
