### ISSUE TITLE
module 'sqlite3' has no attribute 'DatabaseError'

### ISSUE THREAD

**Issue by fredzannarbor** [ydataai/pandas-profiling#955]
**Describe the bug**

Simple import of pandas_profiler fails producing the above error.

**To Reproduce**

```
import pandas as pd
from pandas_profiling import ProfileReport

df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
profile = ProfileReport(df)
```

**Version information:**

Python 3.8.5 (default, Jan 29 2021, 15:16:11)
command line, vscode terminal produce same result

<details><summary>Click to expand <strong><em>Version information</em></strong></summary>
<p>

obviously, this is a bit overgrown ...

```
absl-py==0.11.0
affine==2.3.0
aiobotocore==1.4.2
aioftp==0.18.1
aiohttp==3.7.4.post0
aioitertools==0.8.0
alabaster==0.7.12
alembic==1.4.1
altair==4.1.0
altgraph==0.17.2
amazon-paapi5==1.1.2
amightygirl.paapi5-python-sdk==1.0.0
aniso8601==9.0.1
antlr4-python3-runtime==4.8
anyio==3.3.0
anykeystore==0.2
apex==0.9.10.dev0
appdirs==1.4.4
applaunchservices==0.2.1
appnope==0.1.2
APScheduler==3.8.0
arcas==1.0.0
argcomplete==1.12.3
argon2-cffi==20.1.0
arrow==0.5.0
asgiref==3.3.4
asn1crypto==1.4.0
astor==0.8.1
astroid==2.4.2
astropy==4.3.1
astroquery==0.4.3
asttokens==2.0.5
astunparse==1.6.3
async-generator==1.10
async-timeout==3.0.1
atomicwrites==1.4.0
attrs==21.4.0
autocorrect==2.5.1
autopep8==1.5.5
awesome-slugify==1.6.5
aws==0.2.5
azure-core==1.15.0
azure-storage-blob==12.8.1
Babel==2.9.0
backcall==0.2.0
backoff==1.11.1
backports.csv==1.0.7
backports.zoneinfo==0.2.1
base58==2.1.0
bcrypt==3.2.0
beautifulsoup4==4.9.1
bezier==2021.2.12
binaryornot==0.4.4
bip32==2.1
bip44==0.1.1
bitarray==1.2.2
black==20.8b1
bleach==3.3.0
blinker==1.4
blis==0.7.4
blosc==1.10.6
bokeh==2.3.3
booknlp==1.0.7
boto==2.49.0
boto3==1.17.106
botocore==1.20.106
bottlenose==1.1.8
branca==0.4.2
breadability==0.1.20
Brotli==1.0.9
bs4==0.0.1
cached-property==1.5.2
cachetools==4.2.2
catalogue==2.0.6
certifi==2020.12.5
cffi==1.14.4
chardet==3.0.4
charset-normalizer==2.0.10
cheroot==8.5.2
CherryPy==18.6.1
chronology==1.1
click==7.1.2
click-plugins==1.1.1
cligj==0.7.2
cloudpickle==1.6.0
coiled==0.0.58
coincurve==15.0.1
colorama==0.4.4
commonmark==0.9.1
compress-pickle==2.0.1
cookiecutter==1.7.3
coverage==5.4
cryptacular==1.5.5
cryptography==3.3.1
cssselect==1.1.0
cssutils==2.2.0
currency-symbols==2.0.0
CurrencyConverter==0.16.10
cx-Freeze==6.9
cycler==0.10.0
cymem==2.0.5
cytoolz==0.11.2
dash==1.20.0
dash-bootstrap-components==0.12.0
dash-colorscales==0.0.4
dash-core-components==1.16.0
dash-daq==0.5.0
dash-html-components==1.1.3
dash-renderer==1.9.1
dash-table==4.11.3
dask==2021.11.2
databricks-cli==0.14.3
datasets==1.16.1
debugpy==1.3.0
decorator==4.4.2
defusedxml==0.7.1
descartes==1.1.0
diff-match-patch==20200713
dill==0.3.4
Distance==0.1.3
distlib==0.3.1
distributed==2021.11.2
dnspython==2.1.0
-e git+https://github.com/allenai/s2orc-doc2json.git@ba4a145661899a11a86c08f7ebf5d5b0f8bc21db#egg=doc2json
docker==5.0.0
docopt==0.6.2
docutils==0.15.2
docx==0.2.4
docx2json==0.0.10
docx2python==1.27.1
docx2txt==0.8
docxcompose==1.3.1
dominate==2.6.0
dotmap==1.3.23
dtale==1.48.0
ecdsa==0.17.0
efficientnet-pytorch==0.6.3
einops==0.3.2
elastic-apm==6.2.2
elasticsearch==7.10.0
email-validator==1.1.2
en-core-web-lg @ https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-2.3.1/en_core_web_lg-2.3.1.tar.gz
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.2.0/en_core_web_sm-3.2.0-py3-none-any.whl
entrypoints==0.3
et-xmlfile==1.0.1
eth-abi==2.1.1
eth-account==0.5.6
eth-hash==0.3.2
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.10.0
ethereum==2.3.2
executing==0.6.0
extra-streamlit-components==0.1.53
fabric==2.6.0
faiss-cpu==1.7.1.post2
Faker==8.1.4
farm==0.8.0
fastapi==0.65.2
feedparser==6.0.8
filelock==3.0.12
Fiona==1.8.20
fire==0.4.0
flake8==3.8.4
Flask==1.1.2
Flask-Babel==2.0.0
Flask-Compress==1.9.0
Flask-Cors==3.0.10
Flask-Login==0.4.0
Flask-Mail==0.9.1
Flask-Migrate==2.0.2
flask-nav==0.6
flask-ngrok==0.0.25
flask-restplus==0.13.0
Flask-Script==2.0.5
Flask-Sitemap==0.3.0
Flask-SQLAlchemy==2.5.1
Flask-Table==0.5.0
Flask-Uploads==0.2.1
Flask-User==1.0.1.5
Flask-WTF==0.14.2
flatbuffers==1.12
folium==0.12.1.post1
fontmeta==1.6.1
fonttools==4.22.1
forex-python==1.5
fsspec==2021.10.0
ftfy==6.0.3
future==0.18.2
gast==0.3.3
GDAL==3.3.1
gdelt==0.1.10.5.3
gender-guesser==0.4.0
gensim==3.8.3
geopandas==0.9.0
gibberish==0.4.0
gitdb==4.0.7
GitPython==3.1.18
glcontext==2.3.4
-e git+https://github.com/openai/glide-text2im.git@9cc8e563851bd38f5ddb3e305127192cb0f02f5c#egg=glide_text2im
goldpot==0.0.3.4
google-api-core==2.7.2
google-api-python-client==2.44.0
google-auth==1.27.0
google-auth-httplib2==0.1.0
google-auth-oauthlib==0.4.6
google-cloud-bigquery==2.30.1
google-cloud-core==2.0.0
google-cloud-firestore==2.3.2
google-crc32c==1.3.0
google-pasta==0.2.0
google-resumable-media==2.1.0
googleapis-common-protos==1.53.0
graphviz==0.16
greenlet==1.1.0
grpcio==1.42.0
grpcio-status==1.42.0
grpcio-tools==1.37.1
gunicorn==20.1.0
h11==0.12.0
h5py==2.10.0
hdfs==2.6.0
HeapDict==1.0.1
helpdev==0.7.1
hexbytes==0.2.2
hotstepper==1.0.10
html2image==2.0.1
html5lib==1.1
htmlmin==0.1.12
httplib2==0.19.1
httptools==0.2.0
huggingface-hub==0.2.1
hupper==1.10.2
hydralit==1.0.12
hydralit-components==1.0.9
icecream==2.1.0
idna==2.8
ImageHash==4.2.1
imagesize==1.2.0
importlib-metadata==4.8.2
index-generator==0.3.0
inexactsearch==1.0.2
intervaltree==3.1.0
invoke==1.6.0
ipfshttpclient==0.8.0a2
ipykernel==5.5.0
ipython==7.21.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
isbnlib==3.10.9
isbnlib-loc==1.0.1
isbnlib-worldcat2==0.1.2
isbntools==4.3.27
isodate==0.6.0
isort==5.7.0
itsdangerous==1.1.0
jaraco.classes==3.2.1
jaraco.collections==3.3.0
jaraco.functools==3.3.0
jaraco.text==3.5.1
jedi==0.17.2
jellyfish==0.9.0
Jinja2==2.11.2
jinja2-time==0.2.0
jmespath==0.10.0
joblib==1.0.1
json5==0.9.6
jsonlines==2.0.0
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.12
jupyter-console==6.4.0
jupyter-core==4.7.1
jupyter-server==1.10.2
jupyterlab==3.1.8
jupyterlab-code-formatter==1.4.10
jupyterlab-pygments==0.1.2
jupyterlab-server==2.7.2
jupyterlab-widgets==1.0.0
kaleido==0.2.1
keras==2.7.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
keras-utils==1.0.13
keras2onnx==1.7.0
keyring==23.0.0
kiwisolver==1.3.1
langcodes==3.3.0
langdetect==1.0.7
latex2mathml==2.16.2
lazy-object-proxy==1.4.3
libclang==12.0.0
link-button==1.0.0
llvmlite==0.37.0
locket==0.2.1
lru-dict==1.1.7
lxml==4.6.3
lz4==3.1.3
macholib==1.15.2
Mako==1.1.4
Markdown==3.3.4
markdownify==0.9.4
MarkupSafe==2.0.1
matplotlib==3.4.1
mccabe==0.6.1
memoized-property==1.0.2
mimeparse==0.1.3
missingno==0.4.2
mistune==0.8.4
mlflow==1.13.1
mmh3==3.0.0
mnemonic==0.20
moderngl==5.6.4
mongoengine==0.22.1
more-itertools==8.12.0
mosestokenizer==1.2.1
msgpack==1.0.2
msrest==0.6.21
multiaddr==0.0.9
multidict==5.1.0
multimethod==1.8
multiprocess==0.70.12.2
munch==2.5.0
murmurhash==1.0.5
mwparserfromhell==0.6.3
mypy-extensions==0.4.3
nameparser==1.0.6
nbclassic==0.3.1
nbclient==0.5.3
nbconvert==6.0.7
nbformat==5.1.2
nest-asyncio==1.5.1
netaddr==0.8.0
networkx==2.5.1
nltk==3.7
notebook==6.4.3
numba==0.54.0
numeral==0.1.0.17
numpy==1.18.5
numpy-indexed==0.3.5
numpydoc==1.1.0
oauth==1.0.1
oauth2client==4.1.3
oauthlib==3.1.1
omegaconf==2.1.1
onnx==1.8.1
onnxconverter-common==1.7.0
openai==0.10.2
opencv-python==4.5.4.60
openfile==0.0.7
openpyxl==3.0.7
openpyxl-image-loader==1.0.5
opt-einsum==3.3.0
osmnx==1.0.1
paapi5-python-sdk==1.0.0
packaging==20.9
pandas==1.4.2
pandas-profiling==3.1.0
pandas-stubs==1.2.0.1
pandasgui==0.2.10.1
pandocfilters==1.4.3
paramiko==2.8.0
parfive==1.4.0
parsimonious==0.8.1
parso==0.7.0
partd==1.2.0
passlib==1.7.4
PasteDeploy==2.1.1
pathlib2==2.3.6
pathspec==0.8.1
pathy==0.4.0
patsy==0.5.1
Pattern==3.6
pbkdf2==1.3
pbr==5.5.1
pdf2docx==0.5.1
pdfCropMargins==1.0.5
pdflatex==0.1.3
pdfminer.six==20201018
pdftotext==2.2.0
peewee==3.14.0
pexpect==4.8.0
phik==0.12.2
pickleshare==0.7.5
Pillow==8.1.1
pip-date==1.0.3
pipenv==2020.11.15
pipreqs==0.4.11
plac==1.1.3
plaster==1.0
plaster-pastedeploy==0.7
plotly==4.14.3
pluggy==0.13.1
pnoise==0.1.0
portend==2.7.1
poyo==0.5.0
ppscore==1.2.0
premailer==3.10.0
preshed==3.0.5
pretrainedmodels==0.7.4
prettymaps @ git+https://github.com/marceloprates/prettymaps.git@e9093fae60e4e995c73a7b984da2f9f3f52cf2b0
prettytable==2.2.1
prometheus-client==0.11.0
prometheus-flask-exporter==0.18.2
prompt-toolkit==3.0.18
proto-plus==1.19.0
protobuf==3.15.3
psutil==5.8.0
psycopg2-binary==2.9.1
ptvsd==4.3.2
ptyprocess==0.7.0
py==1.10.0
py-ecc==5.2.0
pyairtable==1.0.0rc3
pyarrow==3.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.6.0
pycountry==20.7.3
pycparser==2.20
pycryptodome==3.10.1
pydantic==1.9.0
pydeck==0.7.0
pyDeprecate==0.3.1
pydocstyle==6.0.0
pyenchant==3.2.2
pyerfa==2.0.0
pyethash==0.1.27
pyflakes==2.2.0
Pygments==2.7.4
pyinstaller==4.7
pyinstaller-hooks-contrib==2021.4
PyJWT==2.1.0
pylint==2.6.2
pyls-black==0.4.6
pyls-spyder==0.3.2
pymilvus==1.1.2
pymongo==3.11.3
Pympler==0.9
PyMuPDF==1.18.9
PyNaCl==1.4.0
pynput==1.7.3
pyobjc==7.1
pyobjc-core==7.1
pyobjc-framework-Accessibility==7.1
pyobjc-framework-Accounts==7.1
pyobjc-framework-AddressBook==7.1
pyobjc-framework-AdServices==7.1
pyobjc-framework-AdSupport==7.1
pyobjc-framework-AppleScriptKit==7.1
pyobjc-framework-AppleScriptObjC==7.1
pyobjc-framework-ApplicationServices==7.1
pyobjc-framework-AppTrackingTransparency==7.1
pyobjc-framework-AuthenticationServices==7.1
pyobjc-framework-AutomaticAssessmentConfiguration==7.1
pyobjc-framework-Automator==7.1
pyobjc-framework-AVFoundation==7.1
pyobjc-framework-AVKit==7.1
pyobjc-framework-BusinessChat==7.1
pyobjc-framework-CalendarStore==7.1
pyobjc-framework-CallKit==7.1
pyobjc-framework-CFNetwork==7.1
pyobjc-framework-ClassKit==7.1
pyobjc-framework-CloudKit==7.1
pyobjc-framework-Cocoa==7.1
pyobjc-framework-Collaboration==7.1
pyobjc-framework-ColorSync==7.1
pyobjc-framework-Contacts==7.1
pyobjc-framework-ContactsUI==7.1
pyobjc-framework-CoreAudio==7.1
pyobjc-framework-CoreAudioKit==7.1
pyobjc-framework-CoreBluetooth==7.1
pyobjc-framework-CoreData==7.1
pyobjc-framework-CoreHaptics==7.1
pyobjc-framework-CoreLocation==7.1
pyobjc-framework-CoreMedia==7.1
pyobjc-framework-CoreMediaIO==7.1
pyobjc-framework-CoreMIDI==7.1
pyobjc-framework-CoreML==7.1
pyobjc-framework-CoreMotion==7.1
pyobjc-framework-CoreServices==7.1
pyobjc-framework-CoreSpotlight==7.1
pyobjc-framework-CoreText==7.1
pyobjc-framework-CoreWLAN==7.1
pyobjc-framework-CryptoTokenKit==7.1
pyobjc-framework-DeviceCheck==7.1
pyobjc-framework-DictionaryServices==7.1
pyobjc-framework-DiscRecording==7.1
pyobjc-framework-DiscRecordingUI==7.1
pyobjc-framework-DiskArbitration==7.1
pyobjc-framework-DVDPlayback==7.1
pyobjc-framework-EventKit==7.1
pyobjc-framework-ExceptionHandling==7.1
pyobjc-framework-ExecutionPolicy==7.1
pyobjc-framework-ExternalAccessory==7.1
pyobjc-framework-FileProvider==7.1
pyobjc-framework-FileProviderUI==7.1
pyobjc-framework-FinderSync==7.1
pyobjc-framework-FSEvents==7.1
pyobjc-framework-GameCenter==7.1
pyobjc-framework-GameController==7.1
pyobjc-framework-GameKit==7.1
pyobjc-framework-GameplayKit==7.1
pyobjc-framework-ImageCaptureCore==7.1
pyobjc-framework-IMServicePlugIn==7.1
pyobjc-framework-InputMethodKit==7.1
pyobjc-framework-InstallerPlugins==7.1
pyobjc-framework-InstantMessage==7.1
pyobjc-framework-Intents==7.1
pyobjc-framework-IOSurface==7.1
pyobjc-framework-iTunesLibrary==7.1
pyobjc-framework-KernelManagement==7.1
pyobjc-framework-LatentSemanticMapping==7.1
pyobjc-framework-LaunchServices==7.1
pyobjc-framework-libdispatch==7.1
pyobjc-framework-LinkPresentation==7.1
pyobjc-framework-LocalAuthentication==7.1
pyobjc-framework-MapKit==7.1
pyobjc-framework-MediaAccessibility==7.1
pyobjc-framework-MediaLibrary==7.1
pyobjc-framework-MediaPlayer==7.1
pyobjc-framework-MediaToolbox==7.1
pyobjc-framework-Metal==7.1
pyobjc-framework-MetalKit==7.1
pyobjc-framework-MetalPerformanceShaders==7.1
pyobjc-framework-MetalPerformanceShadersGraph==7.1
pyobjc-framework-MLCompute==7.1
pyobjc-framework-ModelIO==7.1
pyobjc-framework-MultipeerConnectivity==7.1
pyobjc-framework-NaturalLanguage==7.1
pyobjc-framework-NetFS==7.1
pyobjc-framework-Network==7.1
pyobjc-framework-NetworkExtension==7.1
pyobjc-framework-NotificationCenter==7.1
pyobjc-framework-OpenDirectory==7.1
pyobjc-framework-OSAKit==7.1
pyobjc-framework-OSLog==7.1
pyobjc-framework-PassKit==7.1
pyobjc-framework-PencilKit==7.1
pyobjc-framework-Photos==7.1
pyobjc-framework-PhotosUI==7.1
pyobjc-framework-PreferencePanes==7.1
pyobjc-framework-PushKit==7.1
pyobjc-framework-Quartz==7.1
pyobjc-framework-QuickLookThumbnailing==7.1
pyobjc-framework-ReplayKit==7.1
pyobjc-framework-SafariServices==7.1
pyobjc-framework-SceneKit==7.1
pyobjc-framework-ScreenSaver==7.1
pyobjc-framework-ScreenTime==7.1
pyobjc-framework-ScriptingBridge==7.1
pyobjc-framework-SearchKit==7.1
pyobjc-framework-Security==7.1
pyobjc-framework-SecurityFoundation==7.1
pyobjc-framework-SecurityInterface==7.1
pyobjc-framework-ServiceManagement==7.1
pyobjc-framework-Social==7.1
pyobjc-framework-SoundAnalysis==7.1
pyobjc-framework-Speech==7.1
pyobjc-framework-SpriteKit==7.1
pyobjc-framework-StoreKit==7.1
pyobjc-framework-SyncServices==7.1
pyobjc-framework-SystemConfiguration==7.1
pyobjc-framework-SystemExtensions==7.1
pyobjc-framework-UniformTypeIdentifiers==7.1
pyobjc-framework-UserNotifications==7.1
pyobjc-framework-UserNotificationsUI==7.1
pyobjc-framework-VideoSubscriberAccount==7.1
pyobjc-framework-VideoToolbox==7.1
pyobjc-framework-Virtualization==7.1
pyobjc-framework-Vision==7.1
pyobjc-framework-WebKit==7.1
pyparsing==2.4.7
PyPDF2==1.26.0
pyproj==3.1.0
PyQt5==5.12.3
PyQt5-sip==12.8.1
PyQtWebEngine==5.12.1
pyramid==2.0
pyramid-mailer==0.15.1
pyrsistent==0.17.3
pyscribus==0.2.1
pysha3==1.0.2
PySide2==5.15.2
PySimpleGUI==4.55.1
pyspellchecker==0.6.2
pysqlite3==0.4.7
pytest==3.0.5
pytest-cov==2.4.0
pytextrank==3.1.1
python-amazon-paapi==4.2.2
python-amazon-simple-product-api==2.2.11
python-dateutil==2.8.1
python-docx==0.8.10
python-dotenv==0.19.0
python-editor==1.0.4
python-jose==3.3.0
python-jsonrpc-server==0.4.0
python-language-server==0.36.2
python-Levenshtein==0.12.2
python-louvain==0.15
python-magic==0.4.18
python-multipart==0.0.5
python-slugify==5.0.2
python3-openid==3.2.0
pytorch-lightning==1.5.9
pytorch-transformers==1.2.0
pytz==2021.1
pyvo==1.1
PyWavelets==1.1.1
PyYAML==5.4.1
pyzmq==22.0.3
qasync==0.15.0
QDarkStyle==2.8.1
QtAwesome==1.0.2
qtconsole==5.0.3
QtPy==1.9.0
querystring-parser==1.2.4
raster2xyz==0.1.3
rasterio==1.2.9
ratelimit==1.4.1
rdflib==5.0.0
redis==3.5.3
redislite==6.0.674960
regex==2022.1.18
repoze.lru==0.7
repoze.sendmail==4.4.1
requests==2.27.0
requests-mock==1.9.1
requests-oauthlib==1.3.0
requests-unixsocket==0.2.0
retrying==1.3.3
rich==10.12.0
rlp==1.2.0
rope==0.18.0
rsa==4.7.2
Rtree==0.9.7
s3fs==2021.10.0
s3transfer==0.4.2
sacremoses==0.0.43
scikit-learn==0.24.1
scipy==1.6.2
scrypt==0.8.19
seaborn==0.11.0
segmentation-models-pytorch==0.1.3
segtok==1.5.11
selenium==3.141.0
semver==2.13.0
Send2Trash==1.8.0
sentencepiece==0.1.95
seqeval==0.0.5
sgmllib3k==1.0.0
Shapely==1.7.1
shiboken2==5.15.2
silpa-common==0.3
simplegmail==4.0.3
simplejson==3.17.2
simplify-docx==0.1.0
siuba==0.0.25
six==1.16.0
sklearn==0.0
smart-open==3.0.0
smmap==4.0.0
sniffio==1.2.0
snowballstemmer==2.1.0
snuggs==1.4.7
sortedcontainers==2.3.0
sotawhat @ file:///Users/fred/bin/nimble/openai/nimbleAI/app/utilities/sotawhat/sotawhat
soundex==1.1.3
soupsieve==2.2.1
spacy==3.2.0
spacy-alignments==0.8.4
spacy-langdetect==0.1.2
spacy-legacy==3.0.8
spacy-loggers==1.0.1
spacy-streamlit==0.1.0
spacy-transformers==1.1.2
SPARQLWrapper==1.8.5
Sphinx==3.5.3
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
spyder==4.2.4
spyder-kernels==1.10.2
SQLAlchemy==1.4.19
SQLAlchemy-Utils==0.37.6
sqlite-dump==0.1.1
sqlite-web==0.3.7
sqlparse==0.4.1
squarify==0.4.3
srsly==2.4.2
starlette==0.14.2
statsmodels==0.12.2
stevedore==3.3.0
streamlit==1.8.1
streamlit-aggrid==0.2.1
streamlit-analytics==0.2.2
streamlit-auth0-component==0.0.3
streamlit-bokeh-events==0.1.2
streamlit-folium==0.4.0
streamlit-lottie==0.0.3
streamlit-metrics==0.1.0
streamlit-pandas-profiling==0.1.3
stripe==2.54.0
strsimpy==0.2.0
sumy==0.8.1
sunpy==3.0.1
svg.path==4.1
svgelements==1.5.4
svgwrite==1.4.1
syllables==0.1.0
tabulate==0.8.9
taming-transformers==0.0.1
tangled-up-in-unicode==0.1.0
tblib==1.7.0
tempora==4.1.1
tensorboard==2.7.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.7.0
tensorflow-cpu==2.4.1
tensorflow-estimator==2.7.0
tensorflow-io-gcs-filesystem==0.22.0
termcolor==1.1.0
terminado==0.11.1
testpath==0.4.4
text-unidecode==1.3
textblob==0.15.3
textdistance==4.2.1
thinc==8.0.13
threadpoolctl==2.1.0
three-merge==0.1.1
tidytext==0.0.1
tika==1.24
timm==0.3.2
tokenizers==0.11.6
toml==0.10.2
toolwrapper==2.1.0
toolz==0.11.1
torch==1.8.1
torchmetrics==0.7.0
torchvision==0.9.1
tornado==6.1
tox==3.23.1
tqdm==4.62.3
traitlets==5.0.5
transaction==3.0.1
transformers==4.17.0
translationstring==1.4
typed-ast==1.4.2
typer==0.3.2
typing-extensions==3.7.4.3
tzlocal==2.1
uctools==1.3.0
ujson==4.0.2
Unidecode==0.4.21
uritemplate==3.0.1
urllib3==1.26.7
uvicorn==0.14.0
uvloop==0.14.0
validators==0.18.2
varint==1.0.2
velruse==1.1.1
venusian==3.0.0
virtualenv==20.4.2
virtualenv-clone==0.5.4
virtualenvwrapper==4.8.4
visions==0.7.4
visitor==0.1.3
vpype==1.7.0
vsketch @ git+https://github.com/abey79/vsketch@6d4b4ea1de27ba563032ce1aee02457c16d4ea60
wasabi==0.8.2
watchdog==1.0.2
watchgod==0.7
wcwidth==0.2.5
we-love-colors @ file:///Users/fred/bin/nimble/unity/we-love-colors
weaviate-client==2.5.0
web3==5.25.0
webcolors==1.11.1
webencodings==0.5.1
WebOb==1.8.7
websocket-client==1.1.0
websockets==9.1
Werkzeug==0.16.1
widgetsnbextension==3.5.1
wiki-dump-parser==2.0.2
wikiextractor==3.0.6
wikimapper==0.1.5
wincertstore==0.2
wordcloud==1.8.1
wrapt==1.12.1
WTForms==2.3.3
wtforms-recaptcha==0.3.2
wurlitzer==2.0.1
xarray==0.17.0
xlrd==2.0.1
xls2xlsx==0.1.5
xlutils==2.0.0
xlwt==1.3.0
xmltodict==0.12.0
xxhash==2.0.2
yagmail==0.14.260
yake @ git+https://github.com/LIAAD/yake@238ae58c5ba39326a96862ee0e9cb817e5958440
yapf==0.31.0
yarg==0.1.9
yarl==1.6.3
youtokentome==1.0.6
zc.lockfile==2.0
zict==2.0.0
zipp==3.4.1
zope.deprecation==4.4.0
zope.interface==5.4.0
zope.sqlalchemy==1.3
```

</p>
</details>

**Additional context**
```

/Users/fred/.virtualenvs/unity/bin/python /Users/fred/bin/nimble/unity/app/utilities/testpandasprofile.py
Traceback (most recent call last):
  File "/Users/fred/bin/nimble/unity/app/utilities/testpandasprofile.py", line 2, in <module>
    from pandas_profiling import ProfileReport
  File "/Users/fred/.virtualenvs/unity/lib/python3.8/site-packages/pandas_profiling/__init__.py", line 6, in <module>
    from pandas_profiling.controller import pandas_decorator
  File "/Users/fred/.virtualenvs/unity/lib/python3.8/site-packages/pandas_profiling/controller/pandas_decorator.py", line 4, in <module>
    from pandas_profiling.profile_report import ProfileReport
  File "/Users/fred/.virtualenvs/unity/lib/python3.8/site-packages/pandas_profiling/profile_report.py", line 16, in <module>
    from pandas_profiling.model.describe import describe as describe_df
  File "/Users/fred/.virtualenvs/unity/lib/python3.8/site-packages/pandas_profiling/model/describe.py", line 18, in <module>
    from pandas_profiling.model.pairwise import get_scatter_plot, get_scatter_tasks
  File "/Users/fred/.virtualenvs/unity/lib/python3.8/site-packages/pandas_profiling/model/pairwise.py", line 6, in <module>
    from pandas_profiling.visualisation.plot import scatter_pairwise
  File "/Users/fred/.virtualenvs/unity/lib/python3.8/site-packages/pandas_profiling/visualisation/plot.py", line 7, in <module>
    import seaborn as sns
  File "/Users/fred/.virtualenvs/unity/lib/python3.8/site-packages/seaborn/__init__.py", line 12, in <module>
    from .widgets import *  # noqa: F401,F403
  File "/Users/fred/.virtualenvs/unity/lib/python3.8/site-packages/seaborn/widgets.py", line 7, in <module>
    from ipywidgets import interact, FloatSlider, IntSlider
  File "/Users/fred/.virtualenvs/unity/lib/python3.8/site-packages/ipywidgets/__init__.py", line 23, in <module>
    from IPython import get_ipython
  File "/Users/fred/.virtualenvs/unity/lib/python3.8/site-packages/IPython/__init__.py", line 56, in <module>
    from .terminal.embed import embed
  File "/Users/fred/.virtualenvs/unity/lib/python3.8/site-packages/IPython/terminal/embed.py", line 15, in <module>
    from IPython.core.interactiveshell import DummyMod, InteractiveShell
  File "/Users/fred/.virtualenvs/unity/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 52, in <module>
    from IPython.core.history import HistoryManager
  File "/Users/fred/.virtualenvs/unity/lib/python3.8/site-packages/IPython/core/history.py", line 62, in <module>
    DatabaseError = sqlite3.DatabaseError
AttributeError: module 'sqlite3' has no attribute 'DatabaseError'
(unity) fred@Freds-MacBook-Pro:~/bin/nimble/unity$ 
```

Problem appeared overnight, not sure what changed in the environment.  psgrep for sql shows nothing.

**Comment by sbrugman** [comment]
Thanks for reporting. Have you tried installing in a fresh environment? I'm not aware of any change that could have caused this.

**Comment by fredzannarbor** [comment]
I google around and determined that I had a folder with the same name as
the import. Thanks!
*Nimble Books LLC*
*The AI Lab for Book-Lovers <http://NimbleBooks.com>*
---

**Comment by fabclmnt** [comment]
Closing the issue as this was a folder name issue.
