### ISSUE TITLE
crash when running in python scripts

### ISSUE THREAD

**Issue by kwunlyou** [ydataai/pandas-profiling#993]
### Current Behaviour

output error

Summarize dataset:  27%|█████████                         | 11/41 [00:00<00:02, 13.43it/s, scatter a, a]From cffi callback <function _make_write_func.<locals>.write_func at 0x7f16e8ffa550>:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/cairocffi/surfaces.py", line 47, in write_func
    file_obj.write(ffi.buffer(data, length))
TypeError: string argument expected, got '_cffi_backend.buffer'
Summarize dataset:  27%|█████████                         | 11/41 [00:00<00:02, 12.17it/s, scatter a, a]
Traceback (most recent call last):
  File "research/t.py", line 8, in <module>
    profile.to_file("/tmp/your_report.html")
  File "/opt/conda/lib/python3.8/site-packages/pandas_profiling/profile_report.py", line 257, in to_file
    data = self.to_html()
  File "/opt/conda/lib/python3.8/site-packages/pandas_profiling/profile_report.py", line 368, in to_html
    return self.html
  File "/opt/conda/lib/python3.8/site-packages/pandas_profiling/profile_report.py", line 185, in html
    self._html = self._render_html()
  File "/opt/conda/lib/python3.8/site-packages/pandas_profiling/profile_report.py", line 287, in _render_html
    report = self.report
  File "/opt/conda/lib/python3.8/site-packages/pandas_profiling/profile_report.py", line 179, in report
    self._report = get_report_structure(self.config, self.description_set)
  File "/opt/conda/lib/python3.8/site-packages/pandas_profiling/profile_report.py", line 161, in description_set
    self._description_set = describe_df(
  File "/opt/conda/lib/python3.8/site-packages/pandas_profiling/model/describe.py", line 115, in describe
    scatter_matrix[x][y] = progress(
  File "/opt/conda/lib/python3.8/site-packages/pandas_profiling/utils/progress_bar.py", line 11, in inner
    ret = fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pandas_profiling/model/pairwise.py", line 31, in get_scatter_plot
    return scatter_pairwise(config, df_temp[x], df_temp[y], x, y)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.8/site-packages/pandas_profiling/visualisation/plot.py", line 299, in scatter_pairwise
    return plot_360_n0sc0pe(config)

### Expected Behaviour

the HTML file will be saved

### Data Description

random data

### Code that reproduces the bug

```Python
import numpy as np
import pandas as pd
from pandas_profiling import ProfileReport

df = pd.DataFrame(np.random.rand(100, 5), columns=["a", "b", "c", "d", "e"])

profile = ProfileReport(df, title="Pandas Profiling Report")
profile.to_file("/tmp/your_report.html")
```

### pandas-profiling version

v3.2.0

### Dependencies

```Text
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
absl-py                   0.12.0                   pypi_0    pypi
aiohttp                   3.7.4.post0              pypi_0    pypi
alabaster                 0.7.12                   pypi_0    pypi
altair                    4.2.0                    pypi_0    pypi
analytics-python          1.4.0                    pypi_0    pypi
anyio                     3.0.1                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
argon2-cffi               20.1.0                   pypi_0    pypi
arrow                     1.1.0                    pypi_0    pypi
astroid                   2.5.6                    pypi_0    pypi
astropy                   4.2.1                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
async-generator           1.10                     pypi_0    pypi
async-timeout             3.0.1                    pypi_0    pypi
atomicwrites              1.4.0                    pypi_0    pypi
attrs                     21.2.0                   pypi_0    pypi
automat                   20.2.0                   pypi_0    pypi
autopep8                  1.5.5                    pypi_0    pypi
babel                     2.9.1                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
backoff                   1.10.0                   pypi_0    pypi
backports-shutil-get-terminal-size 1.0.0                    pypi_0    pypi
backports-zoneinfo        0.2.1                    pypi_0    pypi
beautifulsoup4            4.9.3                    pypi_0    pypi
binaryornot               0.4.4                    pypi_0    pypi
bitarray                  2.1.0                    pypi_0    pypi
bkcharts                  0.2                      pypi_0    pypi
black                     21.5b1                   pypi_0    pypi
blaze                     0.10.1                   pypi_0    pypi
bleach                    3.3.0                    pypi_0    pypi
blinker                   1.4                      pypi_0    pypi
bokeh                     2.4.3                    pypi_0    pypi
boto                      2.49.0                   pypi_0    pypi
boto3                     1.23.9                   pypi_0    pypi
botocore                  1.26.9                   pypi_0    pypi
bottleneck                1.3.2                    pypi_0    pypi
brewer2mpl                1.4.1                    pypi_0    pypi
brotli                    1.0.9                    pypi_0    pypi
brotlipy                  0.7.0           py38h27cfd23_1003  
bs4                       0.0.1                    pypi_0    pypi
bson                      0.5.10                   pypi_0    pypi
ca-certificates           2020.12.5            ha878542_0    conda-forge
cachetools                4.2.2                    pypi_0    pypi
cairocffi                 1.2.0                    pypi_0    pypi
certifi                   2020.12.5        py38h578d9bd_1    conda-forge
cffi                      1.14.5           py38h261ae71_0  
chardet                   3.0.4                    pypi_0    pypi
click                     8.0.0                    pypi_0    pypi
cloudpickle               1.6.0                    pypi_0    pypi
clyent                    1.2.1                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
conda                     4.10.1           py38h578d9bd_0    conda-forge
conda-package-handling    1.7.3            py38h27cfd23_1  
configobj                 5.0.6                    pypi_0    pypi
constantly                15.1.0                   pypi_0    pypi
contextlib2               0.6.0.post1              pypi_0    pypi
cookiecutter              1.7.0                    pypi_0    pypi
coverage                  5.5                      pypi_0    pypi
cryptography              3.4.7            py38hd23ed53_0  
cx-oracle                 8.1.0                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.23                  pypi_0    pypi
cytoolz                   0.11.0                   pypi_0    pypi
dask                      2021.4.1                 pypi_0    pypi
datashape                 0.5.2                    pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
deprecated                1.2.13                   pypi_0    pypi
diff-match-patch          20200713                 pypi_0    pypi
distributed               2021.4.1                 pypi_0    pypi
dli                       1.18.0                   pypi_0    pypi
docutils                  0.16                     pypi_0    pypi
editorconfig              0.12.3                   pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
et-xmlfile                1.1.0                    pypi_0    pypi
fastcache                 1.1.0                    pypi_0    pypi
filelock                  3.0.12                   pypi_0    pypi
flake8                    3.8.4                    pypi_0    pypi
flask                     2.0.0                    pypi_0    pypi
flask-compress            1.9.0                    pypi_0    pypi
flask-cors                3.0.10                   pypi_0    pypi
flatbuffers               1.12                     pypi_0    pypi
fsspec                    2021.4.0                 pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
gast                      0.3.3                    pypi_0    pypi
gevent                    21.1.2                   pypi_0    pypi
ggplot                    0.11.5                   pypi_0    pypi
ghp-import                2.1.0                    pypi_0    pypi
gitdb                     4.0.7                    pypi_0    pypi
gitpython                 3.1.14                   pypi_0    pypi
glob2                     0.7                      pypi_0    pypi
gmpy2                     2.0.8                    pypi_0    pypi
google-auth               1.30.0                   pypi_0    pypi
google-auth-oauthlib      0.4.4                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
greenlet                  1.1.0                    pypi_0    pypi
grpcio                    1.32.0                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
heapdict                  1.0.1                    pypi_0    pypi
html5lib                  1.1                      pypi_0    pypi
htmlmin                   0.1.12                   pypi_0    pypi
hyperlink                 21.0.0                   pypi_0    pypi
hypothesis                6.12.0                   pypi_0    pypi
icu                       67.1                 he1b5a44_0    conda-forge
idna                      2.10               pyhd3eb1b0_0  
imagehash                 4.2.1                    pypi_0    pypi
imageio                   2.9.0                    pypi_0    pypi
imagesize                 1.2.0                    pypi_0    pypi
importlib-metadata        4.11.4                   pypi_0    pypi
incremental               21.3.0                   pypi_0    pypi
inflection                0.5.1                    pypi_0    pypi
iniconfig                 1.1.1                    pypi_0    pypi
intervaltree              3.1.0                    pypi_0    pypi
ipykernel                 5.5.4                    pypi_0    pypi
ipython                   7.23.1                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.6.3                    pypi_0    pypi
isort                     5.8.0                    pypi_0    pypi
itsdangerous              2.0.0                    pypi_0    pypi
jansson                   2.13.1               h7f98852_0    conda-forge
jaydebeapi                1.2.3                    pypi_0    pypi
jdcal                     1.4.1                    pypi_0    pypi
jedi                      0.17.2                   pypi_0    pypi
jeepney                   0.6.0                    pypi_0    pypi
jinja2                    3.0.0                    pypi_0    pypi
jinja2-time               0.2.0                    pypi_0    pypi
jmespath                  1.0.0                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
jpype1                    1.2.1                    pypi_0    pypi
jsbeautifier              1.14.3                   pypi_0    pypi
json5                     0.9.5                    pypi_0    pypi
jsonify                   0.5                      pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            6.1.12                   pypi_0    pypi
jupyter-codeserver-proxy  1.0b1                    pypi_0    pypi
jupyter-console           6.4.0                    pypi_0    pypi
jupyter-core              4.7.1                    pypi_0    pypi
jupyter-server            1.7.0                    pypi_0    pypi
jupyter-server-mathjax    0.2.2                    pypi_0    pypi
jupyter-server-proxy      3.0.2                    pypi_0    pypi
jupyterlab                3.0.15                   pypi_0    pypi
jupyterlab-git            0.30.1                   pypi_0    pypi
jupyterlab-pygments       0.1.2                    pypi_0    pypi
jupyterlab-server         2.5.1                    pypi_0    pypi
jupyterlab-widgets        1.0.0                    pypi_0    pypi
keras                     2.7.0                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
keyring                   19.2.0                   pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
lazy-object-proxy         1.6.0                    pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7  
libclang                  14.0.1                   pypi_0    pypi
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgomp                   9.3.0               h2828fa1_19    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libuv                     1.40.0               h7b6447c_0  
libxml2                   2.9.10               h68273f3_2    conda-forge
lightgbm                  3.3.2                    pypi_0    pypi
llvmlite                  0.36.0                   pypi_0    pypi
locket                    0.2.1                    pypi_0    pypi
lxml                      4.6.3                    pypi_0    pypi
markdown                  3.3.4                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.4.2                    pypi_0    pypi
matplotlib-inline         0.1.2                    pypi_0    pypi
mccabe                    0.6.1                    pypi_0    pypi
mergedeep                 1.3.4                    pypi_0    pypi
missingno                 0.5.1                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mitosheet                 0.1.426                  pypi_0    pypi
mkdocs                    1.3.0                    pypi_0    pypi
mkdocs-autorefs           0.4.1                    pypi_0    pypi
mkdocs-material           8.2.15                   pypi_0    pypi
mkdocs-material-extensions 1.0.3                    pypi_0    pypi
mkdocs-mermaid2-plugin    0.6.0                    pypi_0    pypi
mkdocstrings              0.18.1                   pypi_0    pypi
mkdocstrings-python-legacy 0.2.2                    pypi_0    pypi
monotonic                 1.6                      pypi_0    pypi
mpltools                  0.2.0                    pypi_0    pypi
mpmath                    1.2.1                    pypi_0    pypi
msgpack                   1.0.2                    pypi_0    pypi
multidict                 5.1.0                    pypi_0    pypi
multimethod               1.8                      pypi_0    pypi
multipledispatch          0.6.0                    pypi_0    pypi
mypy-extensions           0.4.3                    pypi_0    pypi
nbclassic                 0.2.8                    pypi_0    pypi
nbclient                  0.5.3                    pypi_0    pypi
nbconvert                 6.0.7                    pypi_0    pypi
nbdime                    3.0.0                    pypi_0    pypi
nbformat                  5.1.3                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.5.1                    pypi_0    pypi
networkx                  2.5.1                    pypi_0    pypi
nltk                      3.6.2                    pypi_0    pypi
nodejs                    12.19.0              hdbd6b0a_1    conda-forge
nose                      1.3.7                    pypi_0    pypi
notebook                  6.3.0                    pypi_0    pypi
numba                     0.53.1                   pypi_0    pypi
numexpr                   2.7.3                    pypi_0    pypi
numpy                     1.19.5                   pypi_0    pypi
numpydoc                  1.1.0                    pypi_0    pypi
oauthlib                  3.1.0                    pypi_0    pypi
odo                       0.5.0                    pypi_0    pypi
olefile                   0.46                     pypi_0    pypi
openpyxl                  3.0.7                    pypi_0    pypi
openssl                   1.1.1k               h7f98852_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 21.3                     pypi_0    pypi
pandas                    1.2.4                    pypi_0    pypi
pandas-profiling          3.2.0                    pypi_0    pypi
pandocfilters             1.4.3                    pypi_0    pypi
panel                     0.13.1                   pypi_0    pypi
param                     1.12.1                   pypi_0    pypi
parso                     0.7.0                    pypi_0    pypi
partd                     1.2.0                    pypi_0    pypi
path                      15.1.2                   pypi_0    pypi
path-py                   12.5.0                   pypi_0    pypi
pathlib2                  2.3.5                    pypi_0    pypi
pathspec                  0.8.1                    pypi_0    pypi
patsy                     0.5.1                    pypi_0    pypi
pcre                      8.44                 he1b5a44_0    conda-forge
pep8                      1.7.1                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
phik                      0.12.2                   pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.2.0                    pypi_0    pypi
pip                       21.1.1                   pypi_0    pypi
pkginfo                   1.7.0                    pypi_0    pypi
plotly                    5.8.0                    pypi_0    pypi
pluggy                    0.13.1                   pypi_0    pypi
ply                       3.11                     pypi_0    pypi
polling2                  0.4.6                    pypi_0    pypi
poyo                      0.5.0                    pypi_0    pypi
prometheus-client         0.10.1                   pypi_0    pypi
prompt-toolkit            3.0.18                   pypi_0    pypi
protobuf                  3.16.0                   pypi_0    pypi
psutil                    5.8.0                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
py                        1.10.0                   pypi_0    pypi
py4j                      0.10.9.3                 pypi_0    pypi
pyarrow                   8.0.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycodestyle               2.6.0                    pypi_0    pypi
pycosat                   0.6.3            py38h7b6447c_1  
pycparser                 2.20                       py_2  
pycrypto                  2.6.1                    pypi_0    pypi
pyct                      0.4.8                    pypi_0    pypi
pycurl                    7.43.0.6                 pypi_0    pypi
pydantic                  1.9.1                    pypi_0    pypi
pydeck                    0.7.1                    pypi_0    pypi
pydocstyle                6.0.0                    pypi_0    pypi
pyerfa                    1.7.3                    pypi_0    pypi
pyflakes                  2.2.0                    pypi_0    pypi
pygments                  2.12.0                   pypi_0    pypi
pyhumps                   3.7.1                    pypi_0    pypi
pyjwt                     2.4.0                    pypi_0    pypi
pylint                    2.8.2                    pypi_0    pypi
pyls-black                0.4.6                    pypi_0    pypi
pyls-spyder               0.3.2                    pypi_0    pypi
pymdown-extensions        9.4                      pypi_0    pypi
pympler                   1.0.1                    pypi_0    pypi
pyodbc                    4.0.30                   pypi_0    pypi
pyopenssl                 20.0.1             pyhd3eb1b0_1  
pypandoc                  1.5                      pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyqt5                     5.12.3                   pypi_0    pypi
pyqt5-sip                 12.9.0                   pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.17.3                   pypi_0    pypi
pysocks                   1.7.1            py38h06a4308_0  
pyspark                   3.2.1                    pypi_0    pypi
pytest                    6.2.4                    pypi_0    pypi
pytest-arraydiff          0.3                      pypi_0    pypi
pytest-astropy            0.8.0                    pypi_0    pypi
pytest-astropy-header     0.1.2                    pypi_0    pypi
pytest-cov                2.11.1                   pypi_0    pypi
pytest-doctestplus        0.9.0                    pypi_0    pypi
pytest-filter-subpackage  0.1.1                    pypi_0    pypi
pytest-openfiles          0.5.0                    pypi_0    pypi
pytest-remotedata         0.3.2                    pypi_0    pypi
python                    3.8.8                hdb3f193_5  
python-dateutil           2.8.1                    pypi_0    pypi
python-domino             1.0.4                    pypi_0    pypi
python-dotenv             0.20.0                   pypi_0    pypi
python-json-logger        2.0.2                    pypi_0    pypi
python-jsonrpc-server     0.4.0                    pypi_0    pypi
python-language-server    0.36.2                   pypi_0    pypi
python_abi                3.8                      1_cp38    conda-forge
pytkdocs                  0.16.1                   pypi_0    pypi
pytz                      2021.1                   pypi_0    pypi
pytz-deprecation-shim     0.1.0.post0              pypi_0    pypi
pyviz-comms               2.2.0                    pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pyxdg                     0.27                     pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
pyyaml-env-tag            0.1                      pypi_0    pypi
pyzmq                     22.0.3                   pypi_0    pypi
qdarkstyle                3.0.2                    pypi_0    pypi
qstylizer                 0.2.0                    pypi_0    pypi
qtawesome                 1.0.2                    pypi_0    pypi
qtconsole                 5.1.0                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
readline                  8.1                  h27cfd23_0  
regex                     2021.4.4                 pypi_0    pypi
requests                  2.25.1             pyhd3eb1b0_0  
requests-oauthlib         1.3.0                    pypi_0    pypi
requests-toolbelt         0.9.1                    pypi_0    pypi
rope                      0.19.0                   pypi_0    pypi
rsa                       4.7.2                    pypi_0    pypi
ruamel_yaml               0.15.100         py38h27cfd23_0  
s3transfer                0.5.2                    pypi_0    pypi
scikit-image              0.18.1                   pypi_0    pypi
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.6.3                    pypi_0    pypi
seaborn                   0.11.1                   pypi_0    pypi
secretstorage             3.3.1                    pypi_0    pypi
semver                    2.13.0                   pypi_0    pypi
send2trash                1.5.0                    pypi_0    pypi
service-identity          21.1.0                   pypi_0    pypi
setuptools                52.0.0           py38h06a4308_0  
shap                      0.40.0                   pypi_0    pypi
simpervisor               0.4                      pypi_0    pypi
simplegeneric             0.8.1                    pypi_0    pypi
singledispatch            3.6.1                    pypi_0    pypi
six                       1.15.0           py38h06a4308_0  
slicer                    0.0.7                    pypi_0    pypi
smmap                     4.0.0                    pypi_0    pypi
sniffio                   1.2.0                    pypi_0    pypi
snowballstemmer           2.1.0                    pypi_0    pypi
sortedcollections         2.1.0                    pypi_0    pypi
sortedcontainers          2.3.0                    pypi_0    pypi
soupsieve                 2.2.1                    pypi_0    pypi
sphinx                    3.5.4                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.3                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.4                    pypi_0    pypi
sphinxcontrib-websupport  1.2.4                    pypi_0    pypi
spyder                    5.0.2                    pypi_0    pypi
spyder-kernels            2.0.2                    pypi_0    pypi
sqlalchemy                1.4.15                   pypi_0    pypi
sqlite                    3.35.4               hdfb4753_0  
statsmodels               0.12.2                   pypi_0    pypi
streamlit                 1.9.1                    pypi_0    pypi
sympy                     1.8                      pypi_0    pypi
tables                    3.6.1                    pypi_0    pypi
tabulate                  0.8.9                    pypi_0    pypi
tangled-up-in-unicode     0.2.0                    pypi_0    pypi
tblib                     1.7.0                    pypi_0    pypi
tenacity                  8.0.1                    pypi_0    pypi
tensorboard               2.9.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tensorflow                2.7.0                    pypi_0    pypi
tensorflow-estimator      2.7.0                    pypi_0    pypi
tensorflow-gpu            2.4.1                    pypi_0    pypi
tensorflow-io-gcs-filesystem 0.26.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.9.5                    pypi_0    pypi
testpath                  0.4.4                    pypi_0    pypi
textdistance              4.2.1                    pypi_0    pypi
threadpoolctl             2.1.0                    pypi_0    pypi
three-merge               0.1.1                    pypi_0    pypi
tifffile                  2021.4.8                 pypi_0    pypi
tinycss2                  1.1.0                    pypi_0    pypi
tk                        8.6.10               hbc83047_0  
toml                      0.10.2                   pypi_0    pypi
toolz                     0.11.1                   pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
tqdm                      4.59.0             pyhd3eb1b0_1  
traitlets                 5.0.5                    pypi_0    pypi
twisted                   21.2.0                   pypi_0    pypi
typing-extensions         4.2.0                    pypi_0    pypi
tzdata                    2022.1                   pypi_0    pypi
tzlocal                   4.2                      pypi_0    pypi
ujson                     4.0.2                    pypi_0    pypi
unicodecsv                0.14.1                   pypi_0    pypi
urllib3                   1.26.4             pyhd3eb1b0_0  
uwsgi                     2.0.19.1         py38hd3aacb1_1    conda-forge
validators                0.19.0                   pypi_0    pypi
visions                   0.7.4                    pypi_0    pypi
watchdog                  2.1.8                    pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket                 0.2.1                    pypi_0    pypi
websocket-client          0.59.0                   pypi_0    pypi
werkzeug                  2.0.0                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0  
whichcraft                0.6.1                    pypi_0    pypi
widgetsnbextension        3.5.1                    pypi_0    pypi
wrapt                     1.12.1                   pypi_0    pypi
wurlitzer                 2.1.0                    pypi_0    pypi
xlrd                      2.0.1                    pypi_0    pypi
xlsxwriter                1.4.2                    pypi_0    pypi
xlwt                      1.3.0                    pypi_0    pypi
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
yapf                      0.31.0                   pypi_0    pypi
yarl                      1.6.3                    pypi_0    pypi
zict                      2.0.0                    pypi_0    pypi
zipp                      3.4.1                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  
zope-event                4.5.0                    pypi_0    pypi
zope-interface            5.4.0                    pypi_0    pypi
```

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by sbrugman** [comment]
@kwunlyou The issue seems to be with `cairocffi` and capturing the matplotlib output. Could you try with a new environment, and/or updating/removing `cairocffi`?

**Comment by kwunlyou** [comment]
@sbrugman Thanks. You're right. A fresh minimum environment with the latest dependencies can solve the issue.

**Comment by sbrugman** [comment]
No problem, happy that your issue has bren resolved
